apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: tinpb/udagram-frontend:v2
        name: udagram-frontend
        resources:
          requests:
              memory: "64Mi"
              cpu: "250m"
          limits:
              memory: "2Gi"
              cpu: "500m"        
status: {}
